# Generated by Django 5.2 on 2025-06-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pravahapp', '0002_jobapplication_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
