# Generated by Django 5.2 on 2025-04-24 09:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pravahapp', '0002_customuser_registered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='registered_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
