# Generated by Django 5.2 on 2025-06-21 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pravahapp', '0003_jobapplication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='status',
        ),
    ]
