# Generated by Django 5.2 on 2025-06-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pravahapp', '0004_remove_jobapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='applied_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
