# Generated by Django 5.2 on 2025-07-03 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pravahapp', '0007_jobapplication_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s]+$', 'Username must contain only letters and spaces.')]),
        ),
    ]
